# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-14 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezpz', '0003_auto_20170714_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('date_created', models.DateTimeField()),
                ('priority', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date_created',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
