# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-15 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezpz', '0004_auto_20170714_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefeedback',
            name='category',
            field=models.CharField(max_length=65536, null=True),
        ),
    ]
